### ISSUE TITLE
error for  pgrest command

### ISSUE THREAD

**Issue by arunr307** [pgrest/pgrest#78]
hello,
its showing error for me when giving a command :- pgrest --db test 
\
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: fe_sendauth: no password supplied

    at Connection.<anonymous> (/usr/lib/node_modules/pgrest/node_modules/plv8x/node_modules/pg/lib/native/index.js:202:17)
    at Connection.emit (events.js:95:17)

**Comment by jelitox** [comment]
hello, @arunr307 you find a way to get working?

**Comment by arunr307** [comment]
@jelitox  no......Did you have any idea?
